/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ModelsCollection;
import org.openapitools.client.model.ModelsProperty;
import org.openapitools.client.model.RestHTTPError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CollectionsApi
 */
@Disabled
public class CollectionsApiTest {

    private final CollectionsApi api = new CollectionsApi();

    /**
     * Add collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCollectionTest() throws ApiException {
        ModelsCollection modelsCollection = null;
        String format = null;
        List<String> options = null;
        ModelsCollection response = api.addCollection(modelsCollection, format, options);
        // TODO: test validations
    }

    /**
     * Add collection property
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addCollectionPropertyTest() throws ApiException {
        String collection = null;
        String property = null;
        ModelsProperty modelsProperty = null;
        ModelsProperty response = api.addCollectionProperty(collection, property, modelsProperty);
        // TODO: test validations
    }

    /**
     * Delete collection
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCollectionTest() throws ApiException {
        String collection = null;
        api.deleteCollection(collection);
        // TODO: test validations
    }

    /**
     * Delete collection property
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCollectionPropertyTest() throws ApiException {
        String collection = null;
        String property = null;
        api.deleteCollectionProperty(collection, property);
        // TODO: test validations
    }

    /**
     * List collections
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllCollectionsTest() throws ApiException {
        String format = null;
        List<String> options = null;
        List<ModelsCollection> response = api.getAllCollections(format, options);
        // TODO: test validations
    }

    /**
     * Get collection details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCollectionTest() throws ApiException {
        String collection = null;
        String format = null;
        List<String> options = null;
        ModelsCollection response = api.getCollection(collection, format, options);
        // TODO: test validations
    }

    /**
     * Get collection property
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCollectionPropertyTest() throws ApiException {
        String collection = null;
        String property = null;
        ModelsProperty response = api.getCollectionProperty(collection, property);
        // TODO: test validations
    }

    /**
     * List collection properties
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCollectionPropertiesTest() throws ApiException {
        String collection = null;
        List<String> options = null;
        List<ModelsProperty> response = api.listCollectionProperties(collection, options);
        // TODO: test validations
    }

    /**
     * Update collection details
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCollectionTest() throws ApiException {
        String collection = null;
        ModelsCollection modelsCollection = null;
        String format = null;
        List<String> options = null;
        ModelsCollection response = api.updateCollection(collection, modelsCollection, format, options);
        // TODO: test validations
    }

    /**
     * Update collection property
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCollectionPropertyTest() throws ApiException {
        String collection = null;
        String property = null;
        ModelsProperty modelsProperty = null;
        api.updateCollectionProperty(collection, property, modelsProperty);
        // TODO: test validations
    }

}
