/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ModelsConfVar;
import org.openapitools.client.model.ModelsConfVarValue;
import org.openapitools.client.model.RestHTTPError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigVarsApi
 */
@Disabled
public class ConfigVarsApiTest {

    private final ConfigVarsApi api = new ConfigVarsApi();

    /**
     * Clear configuration variables
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void clearAllConfVarsTest() throws ApiException {
        api.clearAllConfVars();
        // TODO: test validations
    }

    /**
     * Get configuration variable
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConfVarTest() throws ApiException {
        String name = null;
        ModelsConfVar response = api.getConfVar(name);
        // TODO: test validations
    }

    /**
     * Set configuration variable
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void setConfVarTest() throws ApiException {
        String name = null;
        ModelsConfVarValue modelsConfVarValue = null;
        api.setConfVar(name, modelsConfVarValue);
        // TODO: test validations
    }

}
