/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConfigService
 */
public class ConfigServiceTest {
    private final ConfigService model = new ConfigService();

    /**
     * Model tests for ConfigService
     */
    @Test
    public void testConfigService() {
        // TODO: test ConfigService
    }

    /**
     * Test the property 'adminApiKey'
     */
    @Test
    public void adminApiKeyTest() {
        // TODO: test adminApiKey
    }

    /**
     * Test the property 'adminMayReadData'
     */
    @Test
    public void adminMayReadDataTest() {
        // TODO: test adminMayReadData
    }

    /**
     * Test the property 'defaultPageSize'
     */
    @Test
    public void defaultPageSizeTest() {
        // TODO: test defaultPageSize
    }

    /**
     * Test the property 'forceAccessReason'
     */
    @Test
    public void forceAccessReasonTest() {
        // TODO: test forceAccessReason
    }

    /**
     * Test the property 'listenAddr'
     */
    @Test
    public void listenAddrTest() {
        // TODO: test listenAddr
    }

    /**
     * Test the property 'maxPageSize'
     */
    @Test
    public void maxPageSizeTest() {
        // TODO: test maxPageSize
    }

    /**
     * Test the property 'timeoutSeconds'
     */
    @Test
    public void timeoutSecondsTest() {
        // TODO: test timeoutSeconds
    }

    /**
     * Test the property 'cacheRefreshIntervalSeconds'
     */
    @Test
    public void cacheRefreshIntervalSecondsTest() {
        // TODO: test cacheRefreshIntervalSeconds
    }

    /**
     * Test the property 'license'
     */
    @Test
    public void licenseTest() {
        // TODO: test license
    }

}
