/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConfigMigration
 */
public class ConfigMigrationTest {
    private final ConfigMigration model = new ConfigMigration();

    /**
     * Model tests for ConfigMigration
     */
    @Test
    public void testConfigMigration() {
        // TODO: test ConfigMigration
    }

    /**
     * Test the property 'autoRun'
     */
    @Test
    public void autoRunTest() {
        // TODO: test autoRun
    }

    /**
     * Test the property 'enableRetries'
     */
    @Test
    public void enableRetriesTest() {
        // TODO: test enableRetries
    }

    /**
     * Test the property 'initialWaitBetweenRetries'
     */
    @Test
    public void initialWaitBetweenRetriesTest() {
        // TODO: test initialWaitBetweenRetries
    }

    /**
     * Test the property 'maxRetries'
     */
    @Test
    public void maxRetriesTest() {
        // TODO: test maxRetries
    }

    /**
     * Test the property 'maxWaitBetweenRetries'
     */
    @Test
    public void maxWaitBetweenRetriesTest() {
        // TODO: test maxWaitBetweenRetries
    }

}
