/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ModelsTokenAggregatedMetadata;
import org.openapitools.client.model.ModelsTokenRefMetadata;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsTokenMetadata
 */
public class ModelsTokenMetadataTest {
    private final ModelsTokenMetadata model = new ModelsTokenMetadata();

    /**
     * Model tests for ModelsTokenMetadata
     */
    @Test
    public void testModelsTokenMetadata() {
        // TODO: test ModelsTokenMetadata
    }

    /**
     * Test the property 'agg'
     */
    @Test
    public void aggTest() {
        // TODO: test agg
    }

    /**
     * Test the property 'reusableTokenId'
     */
    @Test
    public void reusableTokenIdTest() {
        // TODO: test reusableTokenId
    }

    /**
     * Test the property 'reversible'
     */
    @Test
    public void reversibleTest() {
        // TODO: test reversible
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'tokenId'
     */
    @Test
    public void tokenIdTest() {
        // TODO: test tokenId
    }

    /**
     * Test the property 'tokens'
     */
    @Test
    public void tokensTest() {
        // TODO: test tokens
    }

}
