/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsWorker
 */
public class ModelsWorkerTest {
    private final ModelsWorker model = new ModelsWorker();

    /**
     * Model tests for ModelsWorker
     */
    @Test
    public void testModelsWorker() {
        // TODO: test ModelsWorker
    }

    /**
     * Test the property 'workerId'
     */
    @Test
    public void workerIdTest() {
        // TODO: test workerId
    }

    /**
     * Test the property 'generationNumber'
     */
    @Test
    public void generationNumberTest() {
        // TODO: test generationNumber
    }

    /**
     * Test the property 'modifiedAt'
     */
    @Test
    public void modifiedAtTest() {
        // TODO: test modifiedAt
    }

    /**
     * Test the property 'refreshIntervalSeconds'
     */
    @Test
    public void refreshIntervalSecondsTest() {
        // TODO: test refreshIntervalSeconds
    }

}
