/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ModelsProductVersion
 */
public class ModelsProductVersionTest {
    private final ModelsProductVersion model = new ModelsProductVersion();

    /**
     * Model tests for ModelsProductVersion
     */
    @Test
    public void testModelsProductVersion() {
        // TODO: test ModelsProductVersion
    }

    /**
     * Test the property 'dbSchemaVersion'
     */
    @Test
    public void dbSchemaVersionTest() {
        // TODO: test dbSchemaVersion
    }

    /**
     * Test the property 'vaultId'
     */
    @Test
    public void vaultIdTest() {
        // TODO: test vaultId
    }

    /**
     * Test the property 'vaultVersion'
     */
    @Test
    public void vaultVersionTest() {
        // TODO: test vaultVersion
    }

}
