/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ConfigFeatures
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-03T07:11:51.536091Z[Etc/UTC]")
public class ConfigFeatures {
  public static final String SERIALIZED_NAME_API_KEY_HASHING = "api_key_hashing";
  @SerializedName(SERIALIZED_NAME_API_KEY_HASHING)
  private Boolean apiKeyHashing;

  public static final String SERIALIZED_NAME_ENCRYPTION = "encryption";
  @SerializedName(SERIALIZED_NAME_ENCRYPTION)
  private Boolean encryption;

  public static final String SERIALIZED_NAME_POLICY_ENFORCEMENT = "policy_enforcement";
  @SerializedName(SERIALIZED_NAME_POLICY_ENFORCEMENT)
  private Boolean policyEnforcement;

  public static final String SERIALIZED_NAME_MASK_LICENSE = "mask_license";
  @SerializedName(SERIALIZED_NAME_MASK_LICENSE)
  private Boolean maskLicense;

  public ConfigFeatures() {
  }

  public ConfigFeatures apiKeyHashing(Boolean apiKeyHashing) {
    
    this.apiKeyHashing = apiKeyHashing;
    return this;
  }

   /**
   * Get apiKeyHashing
   * @return apiKeyHashing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getApiKeyHashing() {
    return apiKeyHashing;
  }


  public void setApiKeyHashing(Boolean apiKeyHashing) {
    this.apiKeyHashing = apiKeyHashing;
  }


  public ConfigFeatures encryption(Boolean encryption) {
    
    this.encryption = encryption;
    return this;
  }

   /**
   * Get encryption
   * @return encryption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEncryption() {
    return encryption;
  }


  public void setEncryption(Boolean encryption) {
    this.encryption = encryption;
  }


  public ConfigFeatures policyEnforcement(Boolean policyEnforcement) {
    
    this.policyEnforcement = policyEnforcement;
    return this;
  }

   /**
   * Get policyEnforcement
   * @return policyEnforcement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPolicyEnforcement() {
    return policyEnforcement;
  }


  public void setPolicyEnforcement(Boolean policyEnforcement) {
    this.policyEnforcement = policyEnforcement;
  }


  public ConfigFeatures maskLicense(Boolean maskLicense) {
    
    this.maskLicense = maskLicense;
    return this;
  }

   /**
   * Get maskLicense
   * @return maskLicense
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getMaskLicense() {
    return maskLicense;
  }


  public void setMaskLicense(Boolean maskLicense) {
    this.maskLicense = maskLicense;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigFeatures configFeatures = (ConfigFeatures) o;
    return Objects.equals(this.apiKeyHashing, configFeatures.apiKeyHashing) &&
        Objects.equals(this.encryption, configFeatures.encryption) &&
        Objects.equals(this.policyEnforcement, configFeatures.policyEnforcement) &&
        Objects.equals(this.maskLicense, configFeatures.maskLicense);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKeyHashing, encryption, policyEnforcement, maskLicense);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigFeatures {\n");
    sb.append("    apiKeyHashing: ").append(toIndentedString(apiKeyHashing)).append("\n");
    sb.append("    encryption: ").append(toIndentedString(encryption)).append("\n");
    sb.append("    policyEnforcement: ").append(toIndentedString(policyEnforcement)).append("\n");
    sb.append("    maskLicense: ").append(toIndentedString(maskLicense)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("api_key_hashing");
    openapiFields.add("encryption");
    openapiFields.add("policy_enforcement");
    openapiFields.add("mask_license");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConfigFeatures
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ConfigFeatures.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConfigFeatures is not found in the empty JSON string", ConfigFeatures.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ConfigFeatures.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConfigFeatures` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfigFeatures.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfigFeatures' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfigFeatures> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfigFeatures.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfigFeatures>() {
           @Override
           public void write(JsonWriter out, ConfigFeatures value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConfigFeatures read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConfigFeatures given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConfigFeatures
  * @throws IOException if the JSON string is invalid with respect to ConfigFeatures
  */
  public static ConfigFeatures fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfigFeatures.class);
  }

 /**
  * Convert an instance of ConfigFeatures to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

