/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ConfigTTL
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-03T07:11:51.536091Z[Etc/UTC]")
public class ConfigTTL {
  public static final String SERIALIZED_NAME_ASSOCIATED_OBJECTS = "associated_objects";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_OBJECTS)
  private Integer associatedObjects;

  public static final String SERIALIZED_NAME_TOKENS = "tokens";
  @SerializedName(SERIALIZED_NAME_TOKENS)
  private Integer tokens;

  public static final String SERIALIZED_NAME_UNASSOCIATED_OBJECTS = "unassociated_objects";
  @SerializedName(SERIALIZED_NAME_UNASSOCIATED_OBJECTS)
  private Integer unassociatedObjects;

  public ConfigTTL() {
  }

  public ConfigTTL associatedObjects(Integer associatedObjects) {
    
    this.associatedObjects = associatedObjects;
    return this;
  }

   /**
   * Get associatedObjects
   * @return associatedObjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAssociatedObjects() {
    return associatedObjects;
  }


  public void setAssociatedObjects(Integer associatedObjects) {
    this.associatedObjects = associatedObjects;
  }


  public ConfigTTL tokens(Integer tokens) {
    
    this.tokens = tokens;
    return this;
  }

   /**
   * Get tokens
   * @return tokens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTokens() {
    return tokens;
  }


  public void setTokens(Integer tokens) {
    this.tokens = tokens;
  }


  public ConfigTTL unassociatedObjects(Integer unassociatedObjects) {
    
    this.unassociatedObjects = unassociatedObjects;
    return this;
  }

   /**
   * Get unassociatedObjects
   * @return unassociatedObjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getUnassociatedObjects() {
    return unassociatedObjects;
  }


  public void setUnassociatedObjects(Integer unassociatedObjects) {
    this.unassociatedObjects = unassociatedObjects;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigTTL configTTL = (ConfigTTL) o;
    return Objects.equals(this.associatedObjects, configTTL.associatedObjects) &&
        Objects.equals(this.tokens, configTTL.tokens) &&
        Objects.equals(this.unassociatedObjects, configTTL.unassociatedObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associatedObjects, tokens, unassociatedObjects);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigTTL {\n");
    sb.append("    associatedObjects: ").append(toIndentedString(associatedObjects)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    unassociatedObjects: ").append(toIndentedString(unassociatedObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("associated_objects");
    openapiFields.add("tokens");
    openapiFields.add("unassociated_objects");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConfigTTL
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ConfigTTL.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConfigTTL is not found in the empty JSON string", ConfigTTL.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ConfigTTL.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConfigTTL` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfigTTL.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfigTTL' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfigTTL> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfigTTL.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfigTTL>() {
           @Override
           public void write(JsonWriter out, ConfigTTL value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConfigTTL read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConfigTTL given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConfigTTL
  * @throws IOException if the JSON string is invalid with respect to ConfigTTL
  */
  public static ConfigTTL fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfigTTL.class);
  }

 /**
  * Convert an instance of ConfigTTL to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

