/*
 * Piiano Vault REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ModelsConfigurationDoc;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Details of a transformation that can be performed on a PII data type within a collection. Note: &#x60;pii_type_id&#x60; and &#x60;name&#x60; together are also a unique identifier of a transformation in a collection.
 */
@ApiModel(description = "Details of a transformation that can be performed on a PII data type within a collection. Note: `pii_type_id` and `name` together are also a unique identifier of a transformation in a collection.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-03T07:11:51.536091Z[Etc/UTC]")
public class ModelsTransformationDoc {
  public static final String SERIALIZED_NAME_CONFIGURATION = "configuration";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION)
  private ModelsConfigurationDoc _configuration;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PII_TYPE_NAME = "pii_type_name";
  @SerializedName(SERIALIZED_NAME_PII_TYPE_NAME)
  private String piiTypeName;

  public ModelsTransformationDoc() {
  }

  
  public ModelsTransformationDoc(
     String piiTypeName
  ) {
    this();
    this.piiTypeName = piiTypeName;
  }

  public ModelsTransformationDoc _configuration(ModelsConfigurationDoc _configuration) {
    
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ModelsConfigurationDoc getConfiguration() {
    return _configuration;
  }


  public void setConfiguration(ModelsConfigurationDoc _configuration) {
    this._configuration = _configuration;
  }


  public ModelsTransformationDoc name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of the transformation.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "mask", value = "The name of the transformation.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


   /**
   * The name of the PII type.
   * @return piiTypeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "email", value = "The name of the PII type.")

  public String getPiiTypeName() {
    return piiTypeName;
  }





  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsTransformationDoc modelsTransformationDoc = (ModelsTransformationDoc) o;
    return Objects.equals(this._configuration, modelsTransformationDoc._configuration) &&
        Objects.equals(this.name, modelsTransformationDoc.name) &&
        Objects.equals(this.piiTypeName, modelsTransformationDoc.piiTypeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_configuration, name, piiTypeName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsTransformationDoc {\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    piiTypeName: ").append(toIndentedString(piiTypeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("configuration");
    openapiFields.add("name");
    openapiFields.add("pii_type_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ModelsTransformationDoc
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ModelsTransformationDoc.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModelsTransformationDoc is not found in the empty JSON string", ModelsTransformationDoc.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ModelsTransformationDoc.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ModelsTransformationDoc` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `configuration`
      if (jsonObj.get("configuration") != null && !jsonObj.get("configuration").isJsonNull()) {
        ModelsConfigurationDoc.validateJsonObject(jsonObj.getAsJsonObject("configuration"));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("pii_type_name") != null && !jsonObj.get("pii_type_name").isJsonNull()) && !jsonObj.get("pii_type_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pii_type_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pii_type_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelsTransformationDoc.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelsTransformationDoc' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelsTransformationDoc> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelsTransformationDoc.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelsTransformationDoc>() {
           @Override
           public void write(JsonWriter out, ModelsTransformationDoc value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelsTransformationDoc read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ModelsTransformationDoc given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ModelsTransformationDoc
  * @throws IOException if the JSON string is invalid with respect to ModelsTransformationDoc
  */
  public static ModelsTransformationDoc fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelsTransformationDoc.class);
  }

 /**
  * Convert an instance of ModelsTransformationDoc to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

